export const mutations = {
    LOADING: 'LOADING',
    SET_USER: 'SET_USER',
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    SET_SIGNALS: 'SET_SIGNALS',
    SET_AVAILABLE_SIGNALS: 'SET_AVAILABLE_SIGNALS',
};

export const actions = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    CHECK_AUTH_TOKEN: 'CHECK_AUTH_TOKEN',

    LOAD_SIGNALS: 'LOAD_SIGNALS',
};
